### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1035#1]
Must fix: 

- [ ] Your EDA files should be in your own personal folders. You have no personal folders, just a file for each person instead. 
- [ ] You should flesh out your EDA more by exploring the columns 
- [ ] add a project_function.py 
- [ ] Redo your task 5 as a .ipynb file that includes 1)your research questions 2)the code for the graphs 3)the graphs 4)any conclusions you make 
- [ ] Conduct more analysis in task 5. What you submitted in your docs is insufficient. 
- [ ] Missing task 1, please add it
